kernel: fix: kernel_start should point ss at init data, not code
This bug was causing the recent Ubuntu PPA package (i.e.
fdpp_0.1~beta3-0~201812230223~ubuntu16.04.1_amd64.deb) to
malfunction.  On my Xenial setup, it caused dosemu2 to crash
very shortly after FDPP's starting "123", e.g.

	123ERROR: general protection at 0x7fb46a7c9400: 53